image: maven:latest

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: mvn package

build-dev:
  stage: build
  cache:
    key: build-folder
    policy: push
    paths:
      - ./target
  artifacts:
    name: "app.jar"
    when: always
    expire_in: 2h30min
    paths:
      - ./target/mb-api-*.jar
  script: mvn package -DskipTests
  only:
    - dev

deploy-dev:
  image: docker:latest
  stage: deploy
  cache:
    key: build-folder
    policy: pull
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
  script:
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - docker build -t $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
  only:
    - dev